---
dontChroot: true

timeout: 10

script:
    - command: "mount | grep efivarfs | grep -q ro && mount -n -o remount,rw efivarfs /sys/firmware/efi/efivars || true"

i18n:
    name: "Mounting efivars read-write"
